src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Categorie;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $race;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, minMessage="votre message est trop court")
     */
    private $sexe;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $age;


    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, max=255, minMessage="votre message est trop court")
     */
    private $grand_descriptif;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=255, minMessage="votre message est trop court")
     */
    private $Entente;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="article",cascade={"persist"},orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     */
    private $user;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getRace(): ?string
    {
        return $this->race;
    }

    public function setRace(string $race): self
    {
        $this->race = $race;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getGrandDescriptif(): ?string
    {
        return $this->grand_descriptif;
    }

    public function setGrandDescriptif(string $grand_descriptif): self
    {
        $this->grand_descriptif = $grand_descriptif;

        return $this;
    }

    public function getEntente(): ?string
    {
        return $this->Entente;
    }

    public function setEntente(string $Entente): self
    {
        $this->Entente = $Entente;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setArticle($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getArticle() === $this) {
                $image->setArticle(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }


}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Image;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Notifier\Message\NullMessage;
use Symfony\Component\Notifier\Texter;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{

    //Permet de créer le rendu, et de lui donner le chemin en url (Route)

    /**
     * @Route("/blog", name="blog")
     */
    public function index(Request $request, ArticleRepository $repo, PaginatorInterface $paginator): Response
    {
        $donnees = $repo->findAll();
        $articles = $paginator->paginate(
            $donnees, //on passe les données
            $request->query->getInt('page', 1), // numéro de la page en cour, 1 par default
            2
        );

        return $this->render('blog/index.html.twig', [
            'controller_name' => 'BlogController',
            'title' => 'Liste des animaux',
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function home(ArticleRepository $repo)
    {
        $articles = $repo->findAll();

        return $this->render('blog/home.html.twig', [
            'title' => 'Accueil',
            'articles' => $articles

        ]);
    }

    //---------------------Créer le formulaire de création d'article---------------


    /**
     * @Route("/user/blog/new", name="blog_annonce")
     * @Route("/blog/{id}/edit", name="blog_edit")
     */
    public function createAnnonce(Article $article = null, Request $request, EntityManagerInterface $manager)
    {
        //tests
        // var_dump($article->getUser()->getId());
        // var_dump($this->getUser()->getId());

        // si je n'ai pas d'article(post)
        if (!$article) {
            $article = new Article(); // article vide

        }else{
        //variables 
        $userArticleCreate = $article->getUser()->getId();
        $userConnecte = $this->getUser()->getId();

        // //utilisateur connecté et différent de l'utilisateur qui a crée l'annonce
        if ($userConnecte != $userArticleCreate ) {
            return $this->redirectToRoute("home");

        }

        }

        //direction -> form articletype
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $article->setUser($this->getUser());

            // On récupère les images transmises
            $images = $form->get('image')->getData();

            // On boucle sur les images
            foreach ($images as $image) {
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();

                // On copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // On crée l'image dans la base de données
                $img = new Image();
                $img->setName($fichier);
                $article->addImage($img);
            }
            //si article n'existe pas (date à jour)
            if (!$article->getId()) {
                $article->setcreatedAt(new \DateTime());
            }
            
            $manager->persist($article);
            $manager->flush();
            $this->addFlash('message', 'Annonces crée avc succès');

            return $this->redirectToRoute('blog_show', ['id' => $article->getId()]);
        }
    

        return $this->render('blog/createAnnonce.html.twig', [
            'title' => 'Créer une annonce',
            'formArticle' => $form->createView(),
            'editMode' => $article->getId() !== null,
            'article' => $article
        ]);
    }

    //---------------------on va récupérer l'id de l'article, dans article.---------------


    /**
     * @Route ("/blog/{id}", name="blog_show", requirements={"id":"\d+"})
     */
    public function show(Article $article)
    {


        return $this->render('blog/show.html.twig', [
            'title' => 'annonce',
            'article' => $article
        ]);
    }

    /**
     * @Route("/supprime/image/{id}", name="delete_image", methods={"DELETE"})
     */
    public function deleteImage(Image $image, Request $request)
    {
         $data = json_decode($request->getContent(), true);
         
         if ($this->isCsrfTokenValid('delete'.$image->getId(), $data['_token'])) {
           // on va chercher le nom de l'image
            $nom = $image->getName();

            //on supprime le ficher
            unlink($this->getParameter('images_directory').'/'.$nom);

            //on supprime de la base
            $em = $this->getDoctrine()->getManager();
            $em->remove($image);
            $em->flush();

            //on répond en json
            return new JsonResponse(['success' => 1]);

         }else{
             return new JsonResponse(['error' => 'Token Invalid'], 400);
         }
    }

    /**
     * @Route ("/blog/{id}/delete", name="delete_article")
     */
    public function delete(Article $article)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($article);
        $em->flush();
        
        return $this->redirectToRoute("home");
    }

}

templates/blog/createAnnonce.html.twig
{% extends 'base.html.twig' %}

{% form_theme formArticle 'bootstrap_4_layout.html.twig' %}

{% block body %}

<div class="picture">
    <h1>{{ title }}</h1>
</div>

<!--Début du formulaire-->
{{ form_start(formArticle)}}

    <div class="container">
        {{ form_row(formArticle.prenom, {'attr': {'placeholder': "Entrer le prenom de l'animal *"}}) }}
        {{ form_row(formArticle.categorie) }}
        {{ form_row(formArticle.race, {'attr': {'placeholder': "Entrer la race de l'animal *"}}) }}
        {{ form_row(formArticle.sexe, {'attr': {'placeholder': "Entrer le sexe de l'animal ( male ou femelle ) *"}}) }}
        {{ form_row(formArticle.age, {'attr': {'placeholder': "Entrer l'age de l'animal en chiffre seulement *"}}) }}
        {{ form_row(formArticle.grand_descriptif, {'attr': {'placeholder': "Ecrire un descriptif de l'animal *"}}) }}
        {{ form_row(formArticle.Entente, {'attr': {'placeholder': "Entrer ici si l'animal s'entend avec des animaux si oui lesquels, ou non *"}}) }}
        {{ form_row(formArticle.image, {'attr': {'placeholder': "Inserer une image de l'animal en question *"}}) }}


        <!-- si on modifie on affiche les images qu'il y a dedans en bas de la page -->
        <h3>Images</h3>
        <div>       
             {% for image in article.images %}
        <img src="{{ asset('/uploads/' ~ image.name) }}" width="200" alt="nnn">
        <a href="{{ path('delete_image', {'id': image.id}) }}" 
        data-delete data-token="{{ csrf_token('delete' ~ image.id ) }}">Supprimer</a>
            {% endfor%}
        </div>

        <!-- button qui permet d'enregister ou ajouter -->
        <button class="btn btn-primary mb-4 mt-4" type="submit">
            {% if editMode %}
                Enregister les modification

            {% else %}
                Ajouter l'article

            {% endif %}
        </button>
        
    </div>

    <!--Fin du formulaire-->
    {{ form_end(formArticle)}}
    
    
    {% block javascript %}
        <script src="{{ asset('js/images.js') }}"></script>
    {% endblock %}


{% endblock %}    

templates/blog/home.html.twig
{% extends 'base.html.twig'%}

{% block body %}
<div class="picture">
    <!-- <img src="" id="img" width="1800px" height="500px"> -->
    <h1>{{ title }}</h1>
</div>

<h1 class="text-center mt-4 mb-4">Bienvenue sur Project Association</h1>
<div class="block">
    <p class="text-center">Project association est une platerfome en ligne spécialement dédié pour les réfuges qui peine à faire adopter les animaux abondonnée, et qui non pas de visibilité dans le milieu digital, grâce à project association on compte vous aider pour améliorer la visibilité de votre refuge.</p>
</div>
<div class="containe text-center mt-5">
    <p id="erreur"></p>
    <img src="" id="img" width="400px" height="400px">

</div>

<!-- button vers annonces -->

<div class="block_animals">
    <h2 class="text-center">Retrouvez toutes les annonces des animaux à adopter, ici actuellement {{ articles | length}} annonces se trouve sur notre site</h2>
    

    <a class="btn btn-primary" href="{{ path('blog') }}">Découvrer les animaux</a>
    
</div>

<div class="maps"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d30521.031563372242!2d6.183256656711402!3d48.67722988618648!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1612791594524!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
   
</div>
<div class="boutton text-center">
    <button type="button" class="btn btn-primary btn-lg">Nous contacter</button>
</div>

    {% block javascript %}
        <script src="{{ asset('js/api_image.js') }}"></script>
    {% endblock %}



{% endblock%}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BlogController!{% endblock %}

{% block body %}
<div class="picture">
    <h1>{{ title }}</h1>
</div>

<h2 class="text-center mb-4">il y a {{articles | length}} annonces disponibles sur le site </h2>

<!-- recherche type -->
<div class="d-flex justify-content-center mb-4">
<div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      type
    </button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><a class="dropdown-item" href="#">Something else here</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item" href="#">Separated link</a></li>
    </ul>

    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        lieu
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Separated link</a></li>
      </ul>

      <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        Age
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Separated link</a></li>
      </ul>

  
  </div>
</div>

<!-- Annonces -->
<div class="container">
<div class="row row-cols-1 row-cols-md-3 g-4">

  {% for article in articles %}
        <div class="col mb-4">
        <div class="card">
          {% for image in article.images %}
          <img src="{{ asset('/uploads/' ~ image.name) }}" class="card-img-top" alt="..." height="250" width="370" ">
          {% endfor%}

          <div class="card-body">
            <h5 class="card-title text-center">{{ article.prenom }}</h5>
            <!-- Permet d'afficher les 50 premier caractères du grand descriptif pour donne un avant gout -->
            <p class="card-text">{{ article.grandDescriptif | raw |u.truncate(50, ' ...') }}</p>
            <p> L'annonce a été mis en ligne le : {{ article.createdAt | date('d/n/Y') }}</p>
            <a href="{{ path('blog_show', {'id': article.id}) }}" class="btn btn-primary">Voir l'animal</a>
            </div>
        </div>
        </div>
    {% endfor%}
  </div>
</div>
<div class="container d-flex justify-content-center">
{{ knp_pagination_render(articles) }}
</div>

{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig'%}

{% block body %}
<div class="picture">
    <h1>{{ title }}</h1>
</div>
<h3 class="text-center"> {{ article.prenom}}</h3>


<div class="container d-flex justify-content-center">
    {% for image in article.images %}
    <img src="{{ asset('/uploads/' ~ image.name) }}" width="800" alt="nnn">
    {% endfor%}

</div>
<div class="container mt-5 mb-5">
    
    <!-- Afficher le message de succès -->
    {% for message in app.flashes('message') %}
    <div class="alert alert-success" role="alert">
      {{message}}
    </div>
    {% endfor %}

    <ul class="list-group">
        
        <li class="list-group-item d-flex"><strong>Type : </strong> <p class="ml-2">{{ article.categorie.titre }}</p></li> 
        <li class="list-group-item d-flex"><strong>Race :</strong> <p class="ml-2">{{ article.race}}</p></li> 
        <li class="list-group-item d-flex"><strong>Sexe :</strong> <p class="ml-2">{{ article.sexe}}</p></li> 
        <li class="list-group-item d-flex"><strong>Age :</strong> <p class="ml-2">{{ article.age}}ans</p></li> 
        <li class="list-group-item d-flex"><strong>Descriptif:</strong> <p class="ml-2">{{ article.granddescriptif | raw}}</p></li>
        <li class="list-group-item d-flex"><strong>Entente :</strong> <p class="ml-2"> {{ article.entente}}</p></li> 
        <li class="list-group-item d-flex"><strong>Ville :</strong> <p class="ml-2">{{ article.user.ville}}
        </p></li> 
        <li class="list-group-item d-flex"><strong>Adresse :</strong> <p class="ml-2">1{{ article.user.adresse}}
        </p></li> 
        <li class="list-group-item d-flex"><strong>Numéro :</strong> <p class="ml-2">{{ article.user.numeroTelephone}}
        </p></li> 
    </ul>
    
</div>  

{% endblock%}